# Generated by Django 3.0.7 on 2020-07-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peluquero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=20)),
                ('rubro', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('horario', models.CharField(max_length=30)),
            ],
        ),
    ]
