# Generated by Django 3.0.7 on 2020-07-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200718_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peluquero_info',
            new_name='Peluquero',
        ),
    ]
